Fix for proxy handling, added python 3.8 support, changes in indantation for resulting PKGBUILD
ros-melodic-arch/ros-build-tools-py3 pull request #6
Opened 2020-04-21 12:53 UTC by majorx234

### proxy issue
When using `create_pkgbuild.py` I ran into problems working behind a proxy.
The used library for https handling (`urllib3`) needs in code specification of a proxy as mentioned in the documentation: [https://urllib3.readthedocs.io/en/latest/reference/](https://urllib3.readthedocs.io/en/latest/reference/)
or is shown here: [https://stackoverflow.com/questions/31151615/how-to-handle-proxies-in-urllib3](https://stackoverflow.com/questions/31151615/how-to-handle-proxies-in-urllib3).
A [ProxyManager](https://urllib3.readthedocs.io/en/latest/#proxymanager) is needed in `urllib3`.
Instead I use [Python Request](https://requests.readthedocs.io/en/master/) , because it works with bash proxy variables (e.g. `export http_proxy="http://myproxy:port; https_proxy=...`).
At the moment `urllib3` is still in the code for url parsing (see l.591 in `create_pkgbuild.py`).

### added Python 3.8 support
These includes slight modifications in 2 arrays

### Indentation in PKGBUILD
created PKGBUILD scripts with no extra indentation. I think these came along through better readability of the python source.  

### changes for tarball dir
See in line 356, just spare out the package version in tarball dir, leads to problems in all of my created packages. Is there maybe a new convention for ros git projects?

Thank you for maintaining these packages. 
For further discussion or questions please contact me through gitgub or my email: majorx234@gmail.com (in german or english)
Best regards

2020-05-21 23:49 UTC, acxz commented
Thx for the PR! Sorry for getting back to you so late on this. I'll defer this one to @bionade24

2020-05-23 12:18 UTC, acxz requested changes

2020-05-23 12:18 UTC, acxz commented on PKGBUILD
> +pkgrel=4
Why bumping up two versions, lets just bump this to 3

2020-05-23 12:18 UTC, acxz commented on create_pkgbuild.py
> +            -DCMAKE_BUILD_TYPE=Release \\
Packages shouldn't use `-DCMAKE_BUILD_TYPE=Release` since it resets user config in `/etc/makepkg.conf`

2020-05-23 12:18 UTC, acxz commented on create_pkgbuild.py
> +            -DPYTHON_BASENAME=%(python_basename)s \\
I believe these three lines are deprecated and not needed anymore, See the PKGBUILDs in the rest of the organization as confirmation. Basically ROS packages are not using this cmake variable anymore.

2020-05-23 12:18 UTC, acxz commented on create_pkgbuild.py
> +                             "melodic": ["2.7", "3.7" , "3.8"]}
We can also get rid of 3.7 in these arrays.

2020-05-28 13:59 UTC, bionade24 commented
Thanks @acxz  for pointing out the issues. The script is unmaintained for a long time and I never really used it much. Maybe we should just delete all the crap and make some better than https://github.com/bionade24/ros-aur-helpers and this mess.

2020-05-28 14:59 UTC, majorx234 commented
maybe first we should update this version with @acxz further changes, I use it quiet a lot. for generating most of my PKGBUILD.
But I'm still in the code a we could focus a rewrite

2020-05-28 15:06 UTC, bionade24 commented
> maybe first we should update this version with @acxz further changes, I use it quiet a lot. for generating most of my PKGBUILD.
> But I'm still in the code a we could focus a rewrite
Afaik it still often points to ros-gbp sources. Is this still the case? Otherwise we have to change the source we want from the API, too.

2020-06-11 17:27 UTC, bionade24 commented
@majorx234 Can you please change the wanted things? Otherwise I'll close it soon to merge it with `ros-build-tools`

2020-06-14 20:23 UTC, acxz commented
@majorx234 we have merged the `ros-build-tools-py3` into `ros-build-tools`. If you could open up a PR at new location of `ros-build-tools` [here](https://github.com/acxz/pkgbuilds/tree/master/ros-build-tools) that would be great. If I don't see you create a PR within a week of this comment at the new location. I'll go ahead and apply changes based on this PR.

2020-06-30 12:26 UTC, acxz commented
@majorx234 most of the issues presented here have been resolved at the new location of this codebase: https://github.com/ros-arch/ros-package-tools

The proxy issue has not been tackled, feel free to open a PR at that repo concerning this.

I am going ahead and closing this PR due to inactivity and since ros-package-tools is being maintained in favor of this codebase.

2020-06-30 12:26 UTC, closed without merging